FEM-2505 FB ADS plugin first drop
kaltura/playkit-android-fb-ads pull request #2
Opened 2019-09-01 08:39 UTC by giladna

2019-10-28 13:02 UTC, noamtamim commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInstreamPlugin.java
> +    }
Put everything in try-catch.

2019-12-01 08:58 UTC, noamtamim requested changes

2019-12-01 08:58 UTC, noamtamim commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInStreamAdBreak.java
> +                if (fbInStreamAdList.get(indx) != null) {
Extract variable `fbInStreamAdList.get(indx)`.

2019-12-01 08:58 UTC, noamtamim commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInstreamPlugin.java
> +        //timer.cancel();
Remove

2019-12-01 08:58 UTC, noamtamim commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInstreamPlugin.java
> +        //cancelTimer();
Remove

2019-12-01 08:58 UTC, noamtamim commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInstreamPlugin.java
> +        //cancelTimer();
Remove

2019-12-01 09:03 UTC, giladna commented on fbadsplugin/src/main/java/com/kaltura/playkit/plugins/fbads/fbinstream/FBInStreamAdBreak.java
> +                if (fbInStreamAdList.get(indx) != null) {
done

2019-12-01 11:29 UTC, noamtamim approved these changes

2019-12-01 12:33 UTC, merged